### ISSUE TITLE
Feature Request: Ability to retrieve a container object by attributes

### ISSUE THREAD

**Issue by CpuID** [xeger/docker-compose#20]
Example: https://github.com/mauricioklein/docker-compose-api/blob/master/README.md

```
compose.get_containers_by(label: 'foo', name: 'bar') # Returns an array of all containers with label = 'foo' and name = bar
```

Right now there doesn't seem to be an ability to fetch an object with the current running container attributes, which is preventing me from using this gem. Would it be possible to get something similar?

**Comment by xeger** [comment]
I prototyped this for you: https://github.com/xeger/docker-compose/pull/21

Let me know if it looks good and I'll finish it off sometime tomorrow.

**Comment by CpuID** [comment]
Thanks! I'll take a look and report back.

**Comment by CpuID** [comment]
@xeger comments in the PR - re one part of the functionality. Otherwise looking good :)
