### ISSUE TITLE
Run Command throwing errors

### ISSUE THREAD

**Issue by mattpickle** [xeger/docker-compose#31]
Not sure what I'm missing, but any command I pass into the run method throws an error.

```
@compose = Docker::Compose.new
@compose.up(detached:true)
```

no such file or directory (Docker::Compose::Error)
```
@compose.run('web', "bin/sh -c echo -n \"Test\"'", detached:true)
```

executable file not found in $PATH
```
@compose.run('web', "rake db:schema:load'", detached:true)
```

**Comment by xeger** [comment]
Sounds like `docker-compose` might not've been in your path. I could do with a better error message, I suppose.
