### ISSUE TITLE
docker-sync will include docker-compose

### ISSUE THREAD

**Issue by EugenMayer** [xeger/docker-compose#33]
I build something which is going to use docker-compose, see https://github.com/EugenMayer/docker_sync or specificly https://github.com/EugenMayer/docker_sync#other-usages-with-docker_sync

I will build docker-compose.rb into docker-sync to have a full-stack support with compose when starting dev stacks.

**Comment by EugenMayer** [comment]
@xeger Implemented here  https://github.com/EugenMayer/docker-sync/wiki/2.2-sync-stack-commands

**Comment by xeger** [comment]
Very nice. You did this without needing to manipulate the YML file contents?

**Comment by EugenMayer** [comment]
For docker-sync-stack yes, thats just the plain "one file' tool. In our development env, where i use docker-sync and docker-compose as libraries to craft our development management tool, i use / make use of the compose overrides / variable injection.

Working effectively with compose overrides needs a level of conventions which you cannot generalize into docker-sync-stack - i guess with some effort you could, but this needs a lot:
 - explaining how overrides would work conceptually and how to design the images to support that for production/development
 - how to create those development files

I might go and create a boilerplate for this at some point, including some support for docker-sync-stack to work with dev/production. Lets see what time i end up having :)
