### ISSUE TITLE
docker-compose parsing issues

### ISSUE THREAD

**Issue by sandrodz** [xeger/docker-compose#40]
OSX sierra:

ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

```
/Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/tasks/stack/stack.thor:6:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:23:in `load'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:23:in `block in <top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:21:in `each'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:21:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/bin/docker-sync-stack:23:in `load'
	from /Users/sandro/.gem/ruby/2.0.0/bin/docker-sync-stack:23:in `<main>'
```

original issue https://github.com/EugenMayer/docker-sync/issues/142#issuecomment-248427303

**Comment by EugenMayer** [comment]
@xeger seems like ruby 2.0 is still either not sufficient enaugh or Sierra ships a special version of it.

**Comment by xeger** [comment]
The gem declares that it requires Ruby 2.1:

https://github.com/xeger/docker-compose/blob/master/docker-compose.gemspec#L22

But it seems that RubyGems does not provide any warning when someone installs it on an older version of Ruby.

Given the number of people who have reported this bug (3-4), it seems obvious that many users prefer the OS X Ruby VM instead of a tool such as rbenv (https://github.com/rbenv/rbenv).

I am considering adding support for Ruby 2.0, but I don't have any free time until next week. I'll leave this issue open to track that effort.

**Comment by xeger** [comment]
In the meantime, @sandrodz, you can install a newer version of Ruby (2.1 or greater) as a workaround. I recommend using rbenv (https://github.com/rbenv/rbenv), but you can also install via Homebrew: https://www.ruby-lang.org/en/documentation/installation/#homebrew

**Comment by sandrodz** [comment]
Well not all developers are ruby devs, and not all of them need rbenv :) Thanks for clarifiication, I will install rbenv, I was meaning to anyways dabbing in ROR.

**Comment by xeger** [comment]
Yup; that's why I am considering re-adding Ruby 2.0 support, so it's easier to use `docker-compose.gem` on a "vanilla" Mac. The changes aren't super intensive; I will probably make them next week and release a new gem version that is compatible.

**Comment by EugenMayer** [comment]
Having 2.0 support would be key for docker-sync to reduce the amount of "prework" needed to try it. Is it possible to even go down to 1.9 for el Captian support?

**Comment by xeger** [comment]
Going to 1.9 would require us to stop using keyword arguments, which would
make the codebase much more ugly and require me to rewrite most of the
tests.

**Comment by EugenMayer** [comment]
I see that, on the other side, OSX users have to install rbenv / ruby to just use docker-sync - that makes me think if i should really stick to the docker-compose gem, since this is a huge hurdle to people actually not wanting to install all this when they are actually planing with docker.

Hard choices

**Comment by sandrodz** [comment]
@EugenMayer people who moved to docker actually don't want anything on their host systems. So it would be better to come up with solution where docker-sync is run inside docker container with correct ruby version, this way avoiding keeping anything on host.

**Comment by EugenMayer** [comment]
this is impossible, docker-sync purpose is to fix what docker-for-mac fails on, it is host-based by defintion

**Comment by xeger** [comment]
I added Ruby 2.0 support in docker-compose 1.0; @sandrodz if you upgrade from 0.8, that should fix your problems.

I added CI coverage to ensure that we remain compatible. See PR @EugenMayer.

**Comment by EugenMayer** [comment]
great, thank you @xeger

**Comment by sandrodz** [comment]
@xeger @EugenMayer thank you both!

Though I've moved to rbenv

**Comment by boedy** [comment]
You forgot changing:

`spec.required_ruby_version = Gem::Requirement.new('~> 2.1')`
to
`spec.required_ruby_version = Gem::Requirement.new('~> 2.0')`
in
https://github.com/xeger/docker-compose/blob/master/docker-compose.gemspec
