### ISSUE TITLE
odd version on rubygems available

### ISSUE THREAD

**Issue by EugenMayer** [xeger/docker-compose#50]
Any idea where 1.4.0 comes from https://github.com/EugenMayer/docker-sync/pull/197 ?

**Comment by EugenMayer** [comment]
@xeger do you have any comments on this? Thanks!

**Comment by xeger** [comment]
D'oh! This was a mistake on my part ... I was releasing a new version of `backticks` at around the same time, and it seems that I got confused between two shell windows, and released the wrong gem!

I never tagged v1.4.0 and its gemspec wasn't coherent (it was marked as 0.4.something). I've yanked it; this should resolve your `docker-sync` problems.

**Comment by EugenMayer** [comment]
great, thanks!
