### ISSUE TITLE
Question: Example of using Rake Tasks?

### ISSUE THREAD

**Issue by flyinbutrs** [xeger/docker-compose#64]
Hi, I'm writing a rakefile right now to simplify our docker development process. Is there an example of using ```Docker::Compose::RakeTasks```? I've read the docs and the readme, and I can't wrap my head around how to use it, or what it gets me over putting an instance of ```Docker::Compose``` in a separate rake task.

Thanks!

**Comment by xeger** [comment]
When you instantiate a `RakeTasks` inside your Makefile, it defines a few tasks which you should see in the `rake -T` output. You can customize the way the tasks behave to a degree; if I wanted to change the Rakefile name used by my tasks:

```
Docker::Compose::RakeTasks.new do |tasks|
    tasks.file = 'NotADockerfile'
    tasks.rake_namespace = 'booga:flim'
end
```

As for what these tasks do: they help with a very common use case that involves "gluing" a host-based process (e.g. a dev server) to companion services that run in containers. This is generally more convenient than stuffing your dev code into a container, especially for scripting languages e.g. Ruby.

The `docker:compose:env` task prints out some environment variables that point your host app to the randomly mapped container ports; just [tell the gem which variables you need](https://github.com/xeger/docker-compose/blob/master/lib/docker/compose/rake_tasks.rb#L35). If I had a container named `mysqlserver` exposing port 3306 that was randomly mapped to 12345, I could pass some DB inputs to my app:

```
tasks.host_env = {'DB_HOST': 'mysqlserver:[3306]', 'DB_PORT': '[mysqlserver]:3306', 'DB_URL': 'mysql://mysqlserver:3306'}
```

If I want to run a dev server, I can `eval (rake docker:compose:env)` and then invoke a server, or I can use `docker:compose:server` to run one for me.

These rake commands remain consistent between projects which enhances productivity. However, the job they do isn't useful to everyone; it depends on your use case for Docker::Compose. If you can achieve the same thing by calling a session inside your own rake commands, then go for it!

**Comment by flyinbutrs** [comment]
Understood, thanks! I ended up doing my rake tasks with just system calls to docker-compose though because it was simpler.
