### ISSUE TITLE
Docker::Compose::Session#run always requires a command

### ISSUE THREAD

**Issue by bilby91** [xeger/docker-compose#69]
`docker-compose run service_name` can be called without an explicit command. When no command is given, compose will use the `command` key in the docker-compose specification or default to the CMD in the Dockerfile definition if one was given at build time. 

I think that `command` should be optional but based on how the api works right now, making the command optional will be a breaking change.

Thoughts @xeger ?

**Comment by xeger** [comment]
Are you sure this isn't supported right now? The method signature uses a position glob `*cmd` so in theory, it should be legal to pass 0 extra params to `Session#run`. (You'd still need to provide the service name, but not a command.)

```
 def run(service, *cmd, ...)
```

**Comment by xeger** [comment]
Verified that this (should be) supported; there's a unit test case for it:
```
    it 'runs containers' do
      expect(shell).to receive(:run).with('docker-compose', 'run', {}, 'service1', [])
      session.run('service1')
    end
```
